# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Lincoln&nbsp;virus
description: > # this means to ignore newlines until "baseurl:"
  Lincoln virus - объединение людей со своими хобби и интересами c направленностью на развитие человечества и благотворительности.

meta: Lincoln virus - объединение людей со своими хобби и интересами c направленностью на развитие человечества и благотворительности.

baseurl: "" # the subpath of your site, e.g. /blog
url:  # the base hostname & protocol for your site, e.g. http://example.com
# enforce_ssl: 


total: 5$
total_link_1: https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=T3KLFW2TE8SJC&source=url
total_link_2: https://qiwi.com/n/CHUTKOY
total_link_3: https://money.yandex.ru/to/4100110359631399
total_link_4: https://passport.webmoney.ru/asp/certview.asp?wmid=400086000803

t:
  en:
    menu:
      index:
        name: Home
        url: 
      about_the_virus:
        name: About the virus
        url: about_the_virus/
      projects:
        name: Projects
        url: projects/
      contacts:
        name: Contacts
        url: contacts/
      friends:
        name: Friends of the project
        url: friends/
    friends_btn: Open link
    paginate:
      previous: Previous
      next: Next
      page: Page
      of: of
      previous_news: Previous news
      next_news: Next news
  ru:
    menu:
      index:
        name: Главная
        url: ru/
      about_the_virus:
        name: О вирусе
        url: ru/about_the_virus/
      projects:
        name: Проекты
        url: ru/projects/
      contacts:
        name: Контакты
        url: ru/contacts/
      friends:
        name: Друзья проекта
        url: ru/friends/
    friends_btn: Перейти на сайт
    paginate:
      previous: Назад
      next: Вперёд
      page: Страница
      of: из
      previous_news: Предыдущая новость
      next_news: Следующая новость


collections:
  projects:
    output: true


socials:

  - icon: skype
    link: skype:chutkoy89?call

  - icon: telegram
    link: https://t.me/chutkoy
    
  - icon: facebook-square
    link: https://www.facebook.com/chestnyyeyb89

  - icon: youtube-play
    link: https://www.youtube.com/channel/UCiAxh-kQbW00em5SX1I5n6Q
 

per_page:
  news_list: 4
  ea_list: 6


timezone: Europe/Moscow

# paginate: 4
# paginate_path: "/news/page:num/"

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
  - jekyll-sitemap
  # - jekyll-paginate
  - jemoji
exclude:
  - Gemfile
  - Gemfile.lock
  - .sass-cache
  - .git
  - node_modules
